name: Template CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: "pip" # caching pip dependencies

      - name: Install the library
        run: |
          python3 -m pip install build
          python3 -m build
          python3 -m pip install .

      - name: Run tests
        run: |
          pytest tests